# Generated by Django 2.2.4 on 2021-03-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fans',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
